# Generated by Django 4.2.21 on 2026-04-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('product_id', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('updated_at', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'cart_items',
                'unique_together': {('user_id', 'product_id')},
            },
        ),
    ]
