CREATE DATABASE IF NOT EXISTS ms_staff;
CREATE DATABASE IF NOT EXISTS ms_customer;
CREATE DATABASE IF NOT EXISTS ms_cart;
CREATE DATABASE IF NOT EXISTS ms_payment;
CREATE DATABASE IF NOT EXISTS ms_shipping;
CREATE DATABASE IF NOT EXISTS ms_user;
