# Generated by Django 4.2.21 on 2026-04-28 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('user_id', models.IntegerField()),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('total', models.FloatField(default=0.0)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('created_at', models.CharField(blank=True, max_length=100, null=True)),
                ('completed_at', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('quantity', models.IntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order_app.order')),
            ],
            options={
                'db_table': 'order_items',
            },
        ),
    ]
