# Generated by Django 4.2.21 on 2026-04-28 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product_service.category')),
            ],
        ),
        migrations.CreateModel(
            name='Watches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water', models.CharField(blank=True, max_length=50, null=True)),
                ('shock', models.CharField(blank=True, max_length=50, null=True)),
                ('movement', models.CharField(blank=True, max_length=50, null=True)),
                ('os', models.CharField(blank=True, max_length=50, null=True)),
                ('style', models.CharField(blank=True, max_length=50, null=True)),
                ('lume', models.CharField(blank=True, max_length=50, null=True)),
                ('iconic', models.BooleanField(blank=True, null=True)),
                ('classic', models.BooleanField(blank=True, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='watches_details', to='product_service.product')),
            ],
        ),
        migrations.CreateModel(
            name='Sportswear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech', models.CharField(blank=True, max_length=50, null=True)),
                ('feel', models.CharField(blank=True, max_length=50, null=True)),
                ('dry', models.CharField(blank=True, max_length=50, null=True)),
                ('waterproof', models.BooleanField(blank=True, null=True)),
                ('capacity', models.CharField(blank=True, max_length=50, null=True)),
                ('retro', models.BooleanField(blank=True, null=True)),
                ('stretch', models.CharField(blank=True, max_length=50, null=True)),
                ('impact', models.CharField(blank=True, max_length=50, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sportswear_details', to='product_service.product')),
            ],
        ),
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cushion', models.CharField(blank=True, max_length=50, null=True)),
                ('tech', models.CharField(blank=True, max_length=50, null=True)),
                ('style', models.CharField(blank=True, max_length=50, null=True)),
                ('material', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('retro', models.BooleanField(blank=True, null=True)),
                ('weight', models.CharField(blank=True, max_length=50, null=True)),
                ('support', models.CharField(blank=True, max_length=50, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shoes_details', to='product_service.product')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('quantity', models.IntegerField(default=1)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_service.product')),
            ],
            options={
                'db_table': 'purchase_history',
            },
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage', models.CharField(blank=True, max_length=50, null=True)),
                ('camera', models.CharField(blank=True, max_length=50, null=True)),
                ('ram', models.CharField(blank=True, max_length=50, null=True)),
                ('display', models.CharField(blank=True, max_length=50, null=True)),
                ('battery', models.CharField(blank=True, max_length=50, null=True)),
                ('design', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_details', to='product_service.product')),
            ],
        ),
        migrations.CreateModel(
            name='Kitchenware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.CharField(blank=True, max_length=50, null=True)),
                ('preseasoned', models.BooleanField(blank=True, null=True)),
                ('speed', models.IntegerField(blank=True, null=True)),
                ('length', models.CharField(blank=True, max_length=50, null=True)),
                ('power', models.CharField(blank=True, max_length=50, null=True)),
                ('smart', models.BooleanField(blank=True, null=True)),
                ('retro', models.BooleanField(blank=True, null=True)),
                ('temp_control', models.BooleanField(blank=True, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kitchenware_details', to='product_service.product')),
            ],
        ),
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.IntegerField(blank=True, null=True)),
                ('mesh', models.BooleanField(blank=True, null=True)),
                ('wood', models.CharField(blank=True, max_length=50, null=True)),
                ('frame', models.CharField(blank=True, max_length=50, null=True)),
                ('led', models.BooleanField(blank=True, null=True)),
                ('tiers', models.IntegerField(blank=True, null=True)),
                ('eames', models.BooleanField(blank=True, null=True)),
                ('ceramic', models.BooleanField(blank=True, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='furniture_details', to='product_service.product')),
            ],
        ),
        migrations.CreateModel(
            name='Cosmetics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('skintype', models.CharField(blank=True, max_length=50, null=True)),
                ('shades', models.IntegerField(blank=True, null=True)),
                ('waterproof', models.BooleanField(blank=True, null=True)),
                ('colors', models.IntegerField(blank=True, null=True)),
                ('scent', models.CharField(blank=True, max_length=50, null=True)),
                ('pack', models.IntegerField(blank=True, null=True)),
                ('spf', models.IntegerField(blank=True, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cosmetics_details', to='product_service.product')),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.CharField(blank=True, max_length=50, null=True)),
                ('gpu', models.CharField(blank=True, max_length=50, null=True)),
                ('weight', models.CharField(blank=True, max_length=50, null=True)),
                ('durability', models.CharField(blank=True, max_length=100, null=True)),
                ('screen', models.CharField(blank=True, max_length=50, null=True)),
                ('refresh_rate', models.CharField(blank=True, max_length=50, null=True)),
                ('ram', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='computer_details', to='product_service.product')),
            ],
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(blank=True, max_length=100, null=True)),
                ('fit', models.CharField(blank=True, max_length=50, null=True)),
                ('style', models.CharField(blank=True, max_length=50, null=True)),
                ('pattern', models.CharField(blank=True, max_length=50, null=True)),
                ('pockets', models.IntegerField(blank=True, null=True)),
                ('fabric', models.CharField(blank=True, max_length=50, null=True)),
                ('luxury', models.BooleanField(blank=True, null=True)),
                ('temp', models.CharField(blank=True, max_length=50, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clothes_details', to='product_service.product')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(blank=True, max_length=50, null=True)),
                ('selfhelp', models.BooleanField(blank=True, null=True)),
                ('classic', models.BooleanField(blank=True, null=True)),
                ('fantasy', models.BooleanField(blank=True, null=True)),
                ('history', models.BooleanField(blank=True, null=True)),
                ('distopian', models.BooleanField(blank=True, null=True)),
                ('bio', models.BooleanField(blank=True, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='book_details', to='product_service.product')),
            ],
        ),
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lenses', models.CharField(blank=True, max_length=50, null=True)),
                ('rfid', models.BooleanField(blank=True, null=True)),
                ('volume', models.CharField(blank=True, max_length=50, null=True)),
                ('one_size', models.BooleanField(blank=True, null=True)),
                ('material', models.CharField(blank=True, max_length=50, null=True)),
                ('buckle', models.CharField(blank=True, max_length=50, null=True)),
                ('purity', models.CharField(blank=True, max_length=50, null=True)),
                ('portable', models.BooleanField(blank=True, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accessories_details', to='product_service.product')),
            ],
        ),
    ]
