# Generated by Django 4.2.21 on 2026-04-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(unique=True)),
                ('carrier', models.CharField(default='Standard Express', max_length=255)),
                ('status', models.CharField(default='PREPARING', max_length=50)),
                ('created_at', models.CharField(blank=True, max_length=100, null=True)),
                ('delivered_at', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'shipments',
            },
        ),
    ]
